version: "3.8"
services:
  web:
    extra_hosts: host.docker.internal
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
